"""Declarative base, shared column types and mixins.

Two things are established here that everything else depends on.

**A naming convention for constraints.** PostgreSQL will happily invent names
for unnamed constraints, and those names differ between a database built by
``CREATE TABLE`` and one built by a migration. Fixing the convention makes
constraint names deterministic, which makes them assertable in tests and stable
across Alembic autogenerate runs.

**One definition of a money column.** ``NUMERIC(12,2)`` with ``asdecimal=True``,
so a monetary value is a ``Decimal`` from the moment it leaves the database and
a ``float`` can never enter one (architecture.md D§8; ADR-008).
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, Numeric, String, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# --- Shared column types -----------------------------------------------------

#: Monetary amount. Always paired with an explicit currency column (ADR-008).
Money = Numeric(12, 2, asdecimal=True)

#: ISO-4217 alphabetic currency code.
CurrencyCode = String(3)

#: Canonical lowercase token: slugs, compatibility identifiers (ADR-003).
#: The shape is additionally enforced by CHECK constraints on the tables that
#: use it, so a malformed token cannot be inserted at all.
CANONICAL_TOKEN_REGEX = r"^[a-z0-9]+([-_][a-z0-9]+)*$"

#: SKU shape: uppercase alphanumeric with hyphens and underscores, e.g.
#: CASE-IP16-BLK (architecture.md D§10).
SKU_REGEX = r"^[A-Z0-9][A-Z0-9_-]*$"

#: ISO-4217 shape, e.g. INR.
CURRENCY_REGEX = r"^[A-Z]{3}$"


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key, generated by the database when not supplied.

    ``gen_random_uuid()`` is built into PostgreSQL 13 and later, so no extension
    is required. The seed loader supplies its own deterministic UUIDs
    (``app.identifiers``); everything created at runtime gets one from here.
    """
    return mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def fk_uuid(**kwargs: object) -> Mapped[uuid.UUID]:
    """A UUID column used as a foreign key."""
    return mapped_column(PGUUID(as_uuid=True), **kwargs)  # type: ignore[arg-type]


class TimestampMixin:
    """``created_at`` / ``updated_at``, both ``TIMESTAMPTZ`` (D§4 onward).

    Defaults are server-side so that a row inserted by a migration, by the seed
    loader, or by raw SQL is timestamped identically to one inserted by the ORM.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class UpdatedAtMixin:
    """``updated_at`` only.

    ``inventory`` is specified with an ``updated_at`` and no ``created_at``
    (architecture.md D§11). The schema follows the specification rather than
    adding a column for symmetry.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
