"""The Policy Engine (M9) — the last thing that runs before money can move.

    TransactionContext  ->  PolicyEngine.evaluate  ->  PolicyDecision
    (live, locked state)      (pure, ten rules)        (PASS / FAIL + reasons)

P§7 states the property this package exists to hold: *"The result must be
generated by application code. Claude should not be able to override it."* The
engine holds it structurally rather than by wording — it is pure, so it has no
access to anything that could be talked to, and it never reads
`sessions.conversation_state`, so an agent that set that field has changed
nothing an authorization depends on.

`app/policy/` is on the trusted side of ADR-001's boundary alongside
`app/services/`, `app/ranking/` and `app/payments/`. It must never import
`app.llm` or `app.agent`, and a standing test enforces that per file.
"""

from app.domain.policy import LineContext, PolicyDecision, ReasonCode, TransactionContext
from app.policy.engine import MAX_LINE_QUANTITY, PolicyEngine

__all__ = [
    "MAX_LINE_QUANTITY",
    "LineContext",
    "PolicyDecision",
    "PolicyEngine",
    "ReasonCode",
    "TransactionContext",
]
