"""The Policy Engine (M9; P§4–P§8, ADR-011).

The last thing that runs before money can move, and the one component whose
verdict nothing else may override. P§7: *"The result must be generated by
application code. Claude should not be able to override it."*

**It is pure.** Input `TransactionContext`, output `PolicyDecision`. No session,
no query, no clock, no network, no model. That is what makes all ten rules
exhaustively unit-testable without a database, and it is why the engine cannot be
talked into anything: it has no access to anything that could be talked to.

Reading live state is deliberately *not* its job. `OrderService` (M10) reads
prices from `product_variants` and takes `SELECT ... FOR UPDATE` on the inventory
rows, inside the order transaction, and hands the result here. Splitting it that
way means the freshness requirement lives in one place that can be reviewed, and
the decision logic lives in another that can be tested.

**All ten rules are evaluated. Evaluation never stops at the first failure.**
`reason_codes` is a list because the buyer is told everything that is wrong in
one message rather than discovering problems one round-trip at a time — and
because a buyer who fixes the first problem only to meet the second has been
served badly by a system that knew about both.

**The engine never reads `sessions.conversation_state`.** A session says
`APPROVED` only because the agent set it; only a row in `approvals` is evidence
(ADR-007, closing C7). There is no field on `TransactionContext` through which
conversation state could arrive.
"""

from __future__ import annotations

import logging
from dataclasses import replace
from datetime import UTC, datetime
from decimal import Decimal

from app.domain.policy import LineContext, PolicyDecision, ReasonCode, TransactionContext

logger = logging.getLogger(__name__)

__all__ = ["MAX_LINE_QUANTITY", "PolicyEngine"]

#: A§18's bound, re-checked here. The Cart Service already enforces it; this is
#: the check that runs when money is about to move, and it does not trust that
#: the earlier one happened.
MAX_LINE_QUANTITY = 99

#: Statuses that leave a cart orderable. An ORDERED cart has already produced an
#: order; an ABANDONED one has been given up on.
_ORDERABLE_CART_STATUS = "ACTIVE"

#: An idempotency key in this state has already produced an order, so a request
#: presenting it again is a replay rather than a new purchase (ADR-013).
_SPENT_IDEMPOTENCY_STATUSES = frozenset({"COMPLETED"})


class PolicyEngine:
    """Ten rules, evaluated in full, returning a deterministic verdict."""

    def __init__(self, *, spending_limit: Decimal, spending_limit_currency: str = "INR") -> None:
        self._limit = spending_limit
        self._limit_currency = spending_limit_currency

    def evaluate(self, context: TransactionContext) -> PolicyDecision:
        """PASS or FAIL, with every reason the request failed.

        The rules run in P§6's order, which is roughly cheapest-first, but the
        order does not matter to the outcome: every rule runs regardless of what
        the ones before it found.
        """
        # The evaluation instant is resolved onto the context once, rather than
        # threaded through ten rule signatures where one uses it. It also makes
        # the context self-describing: a decision is about a moment, and the
        # moment is now part of the input it was made from.
        ctx = replace(context, evaluated_at=context.evaluated_at or datetime.now(UTC))
        codes: list[ReasonCode] = []
        details: dict[str, str] = {}

        for rule in (
            self._rule_1_approval,
            self._rule_2_cart,
            self._rule_3_products,
            self._rule_4_variants,
            self._rule_5_price,
            self._rule_6_inventory,
            self._rule_7_quantity,
            self._rule_8_spending_limit,
            self._rule_9_existing_order,
            self._rule_10_idempotency,
        ):
            rule(ctx, codes, details)

        # Deduplicated, order preserved: two rules can fail for one underlying
        # cause (a deactivated product fails 3 and its variant fails 4) and a
        # buyer should be told once.
        unique = tuple(dict.fromkeys(codes))
        decision = PolicyDecision(
            decision="FAIL" if unique else "PASS",
            validated_total=ctx.computed_total,
            currency=ctx.currency,
            reason_codes=unique,
            details=details,
        )
        logger.info(
            "policy evaluated",
            extra={
                "cart_id": str(ctx.cart_id),
                "decision": decision.decision,
                "reason_codes": [code.value for code in unique],
            },
        )
        return decision

    # -- 1. user approval ---------------------------------------------------

    def _rule_1_approval(self, ctx, codes, details) -> None:
        """An APPROVED, unexpired, un-superseded approval for this cart version.

        Four distinct ways to fail, one code: from the buyer's side they all mean
        "confirm this again", and telling them which internal state lapsed would
        be telling them about our bookkeeping.
        """
        if ctx.approval_id is None or ctx.approval_status != "APPROVED":
            codes.append(ReasonCode.APPROVAL_REQUIRED)
            details["APPROVAL_REQUIRED"] = "this cart has not been approved"
            return
        if ctx.approval_superseded:
            codes.append(ReasonCode.APPROVAL_REQUIRED)
            details["APPROVAL_REQUIRED"] = "the approval was replaced; please confirm again"
            return
        if ctx.approval_expires_at is not None and ctx.evaluated_at >= ctx.approval_expires_at:
            codes.append(ReasonCode.APPROVAL_REQUIRED)
            details["APPROVAL_REQUIRED"] = "the approval has expired; please confirm again"
            return
        if ctx.approval_cart_version != ctx.current_cart_version:
            codes.append(ReasonCode.APPROVAL_REQUIRED)
            details["APPROVAL_REQUIRED"] = "the cart changed after it was approved"

    # -- 2. cart validity ---------------------------------------------------

    def _rule_2_cart(self, ctx, codes, details) -> None:
        """ACTIVE, non-empty, the claimed version, and the approved composition.

        The fingerprint check is the one that catches a swap the version and the
        total both miss — two carts can reach the same total with different items
        (ADR-007).
        """
        if not ctx.lines:
            codes.append(ReasonCode.INVALID_CART)
            details["INVALID_CART"] = "the cart is empty"
            return
        if ctx.cart_status != _ORDERABLE_CART_STATUS:
            codes.append(ReasonCode.INVALID_CART)
            details["INVALID_CART"] = f"this cart is {ctx.cart_status.lower()}"
            return
        if ctx.cart_version != ctx.current_cart_version:
            codes.append(ReasonCode.INVALID_CART)
            details["INVALID_CART"] = "the cart changed since it was last shown"
            return
        if (
            ctx.approval_fingerprint is not None
            and ctx.current_fingerprint is not None
            and ctx.approval_fingerprint != ctx.current_fingerprint
        ):
            codes.append(ReasonCode.INVALID_CART)
            details["INVALID_CART"] = "the items changed after the cart was approved"

    # -- 3 & 4. product and variant validity --------------------------------

    def _rule_3_products(self, ctx, codes, details) -> None:
        """Every product active, and owned by this merchant.

        Merchant ownership is *checked* rather than assumed. The query that built
        the context was merchant-scoped, and a leak there would be silent; this
        is the defence in depth ADR-005 applies to the ranker for the same
        reason.
        """
        for line in ctx.lines:
            if line.merchant_id != ctx.merchant_id:
                self._invalid_product(line, "is not sold by this merchant", codes, details)
            elif not line.product_is_active:
                self._invalid_product(line, "is no longer available", codes, details)

    def _rule_4_variants(self, ctx, codes, details) -> None:
        for line in ctx.lines:
            if not line.variant_is_active:
                self._invalid_product(line, "is no longer available", codes, details)

    @staticmethod
    def _invalid_product(line: LineContext, why: str, codes, details) -> None:
        codes.append(ReasonCode.INVALID_PRODUCT)
        details["INVALID_PRODUCT"] = f"{line.sku} {why}"

    # -- 5. current price ---------------------------------------------------

    def _rule_5_price(self, ctx, codes, details) -> None:
        """The live total equals `approved_total` **exactly**.

        Both directions (ADR-007, ADR-014, closing D2). A cheaper cart fails
        too: the buyer approved a specific amount, and charging a different one
        is charging an amount that was never authorized. `validated_total` on
        the decision carries the new figure, because that is the number the
        buyer must now be shown (P§7).
        """
        if ctx.approved_total is None:
            return  # rule 1 already reported the missing approval
        live = ctx.computed_total
        if live != ctx.approved_total:
            codes.append(ReasonCode.PRICE_CHANGED)
            details["PRICE_CHANGED"] = (
                f"the total is now {live} {ctx.currency}, "
                f"not the {ctx.approved_total} {ctx.approval_currency or ctx.currency} approved"
            )
        elif ctx.approval_currency is not None and ctx.approval_currency != ctx.currency:
            codes.append(ReasonCode.PRICE_CHANGED)
            details["PRICE_CHANGED"] = "the currency changed since approval"

    # -- 6. current inventory ------------------------------------------------

    def _rule_6_inventory(self, ctx, codes, details) -> None:
        """Live available quantity at or above what was asked, per line.

        Read from a locked row by the caller, so two simultaneous checkouts of
        the last unit serialize: one passes here and the other does not
        (ADR-011, closing C6).
        """
        short = [line for line in ctx.lines if line.available_quantity < line.quantity]
        if short:
            codes.append(ReasonCode.OUT_OF_STOCK)
            details["OUT_OF_STOCK"] = ", ".join(
                f"{line.sku} is no longer available in the quantity requested" for line in short
            )

    # -- 7. quantity ---------------------------------------------------------

    def _rule_7_quantity(self, ctx, codes, details) -> None:
        offenders = [line for line in ctx.lines if not 1 <= line.quantity <= MAX_LINE_QUANTITY]
        if offenders:
            codes.append(ReasonCode.INVALID_CART)
            details["INVALID_CART"] = f"a quantity is outside 1-{MAX_LINE_QUANTITY}: " + ", ".join(
                f"{line.sku} x{line.quantity}" for line in offenders
            )

    # -- 8. spending limit ---------------------------------------------------

    def _rule_8_spending_limit(self, ctx, codes, details) -> None:
        """One global per-transaction ceiling (P§13, closing D3).

        Not per session, not per day, not per merchant — P§13 defers
        merchant-configurable policy until the core system is stable. The value
        is typed configuration, so this test does not depend on the production
        default.
        """
        total = ctx.computed_total
        if total > self._limit:
            codes.append(ReasonCode.SPENDING_LIMIT_EXCEEDED)
            details["SPENDING_LIMIT_EXCEEDED"] = (
                f"{total} {ctx.currency} is above the {self._limit} "
                f"{self._limit_currency} limit for a single purchase"
            )

    # -- 9 & 10. order state and idempotency ---------------------------------

    def _rule_9_existing_order(self, ctx, codes, details) -> None:
        """A cart that already produced an order cannot produce a second."""
        if ctx.existing_order_ids:
            codes.append(ReasonCode.ORDER_ALREADY_EXISTS)
            details["ORDER_ALREADY_EXISTS"] = "an order already exists for this cart"

    def _rule_10_idempotency(self, ctx, codes, details) -> None:
        """A spent key is a replay, not a new purchase (ADR-013).

        Reported rather than silently honoured: the *route* decides to return the
        stored response, and it needs to know this is the case. A rule that
        quietly passed would leave the caller unable to tell a first request from
        a second.
        """
        if ctx.idempotency_status in _SPENT_IDEMPOTENCY_STATUSES:
            codes.append(ReasonCode.ORDER_ALREADY_EXISTS)
            details["ORDER_ALREADY_EXISTS"] = "this request has already been processed"
